[package]
name = "rau"
version = "0.1.0"
authors = ["Brendan Ware"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
archive_library = { path = "archive_library" }
